project_id = "proiyioqfbjcmprsnqhf"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-enrollment-checkout]
verify_jwt = false

[functions.create-store-order-checkout]
verify_jwt = false

[functions.sync-subscription-plan-price]
verify_jwt = true

[functions.generate-pick-lists]
verify_jwt = false

[functions.represcribe-school-year]
verify_jwt = false

[functions.cancel-enrollment]
verify_jwt = true

[functions.portal-cancel-enrollment]
verify_jwt = true

[functions.send-payment-link]
verify_jwt = true

[functions.cancel-store-order]
verify_jwt = true

[functions.submit-website-form]
verify_jwt = false

[functions.student-records-pdf]
verify_jwt = true

[functions.sms-webhooks]
verify_jwt = true

[functions.weekly-summary]
verify_jwt = true

[functions.portal-billing]
verify_jwt = true

[functions.portal-reenroll]
verify_jwt = true
